import React from 'react';
import { Check, X, Share2, Download } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface ModalsProps {
  type: 'success' | 'declined';
  onBack: () => void;
}

const Modals: React.FC<ModalsProps> = ({ type, onBack }) => {
  const isSuccess = type === 'success';

  const transactionData = {
    id: '#9820-X12',
    recipient: 'Abubakar Ahmed',
    amount: '$2,400.00',
    fee: '$0.00',
    total: '$2,400.00',
    date: new Date().toLocaleString(),
  };

  const handleShare = async () => {
    const shareText = `CryptSave Transaction Receipt\nID: ${transactionData.id}\nRecipient: ${transactionData.recipient}\nAmount: ${transactionData.total}\nStatus: Successful`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'CryptSave Receipt',
          text: shareText,
          url: window.location.href,
        });
      } catch (err) {
        console.log('Error sharing:', err);
      }
    } else {
      try {
        await navigator.clipboard.writeText(shareText);
        alert('Receipt details copied to clipboard!');
      } catch (err) {
        console.error('Failed to copy!', err);
      }
    }
  };

  const handleDownload = () => {
    const doc = new jsPDF();
    
    // Background
    doc.setFillColor(10, 10, 11);
    doc.rect(0, 0, 210, 297, 'F');
    
    // Header Logo
    doc.setTextColor(212, 160, 23); // #D4A017 Gold
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("CRYPT SAVE", 105, 40, { align: "center" });
    
    doc.setFontSize(10);
    doc.text("TRANSACTION RECEIPT", 105, 50, { align: "center" });
    
    // Status
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.text(isSuccess ? "PAYMENT SUCCESSFUL" : "PAYMENT DECLINED", 105, 70, { align: "center" });
    
    // Main Amount
    doc.setFontSize(48);
    doc.setTextColor(isSuccess ? 212 : 255, isSuccess ? 160 : 100, isSuccess ? 23 : 100);
    doc.text(transactionData.total, 105, 95, { align: "center" });
    
    // Details Table
    doc.setDrawColor(255, 255, 255);
    doc.setLineWidth(0.1);
    doc.line(40, 110, 170, 110);
    
    const startY = 125;
    const rowHeight = 15;
    const labels = ["Recipient", "Amount", "Network Fee", "Reference ID", "Date"];
    const values = [transactionData.recipient, transactionData.amount, transactionData.fee, transactionData.id, transactionData.date];
    
    doc.setFontSize(12);
    labels.forEach((label, i) => {
      doc.setTextColor(150, 150, 150);
      doc.text(label, 40, startY + (i * rowHeight));
      doc.setTextColor(255, 255, 255);
      doc.text(values[i], 170, startY + (i * rowHeight), { align: "right" });
    });
    
    // Footer
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(8);
    doc.text("Generated by CryptSave Secure Engine • End-to-End Encrypted", 105, 260, { align: "center" });
    
    doc.save(`CryptSave_Receipt_${transactionData.id.replace('#', '')}.pdf`);
  };

  return (
    <div className="h-full w-full bg-black overflow-y-auto no-scrollbar flex flex-col items-center py-10 px-6 lg:py-20">
      <div className="w-full max-w-md bg-[#0A0A0B] rounded-[48px] border border-white/[0.05] shadow-2xl p-8 lg:p-10 flex flex-col items-center relative overflow-hidden shrink-0">
        <div className={`absolute top-0 inset-x-0 h-40 opacity-20 blur-[80px] ${isSuccess ? 'bg-[#D4A017]' : 'bg-red-600'}`} />

        <div className="relative mb-8 mt-4">
          <div className={`w-28 h-28 rounded-full flex items-center justify-center relative z-10 ${isSuccess ? 'bg-[#D4A017]' : 'bg-red-500'}`}>
            {isSuccess ? (
              <Check size={48} className="text-black stroke-[3.5px]" />
            ) : (
              <X size={48} className="text-white stroke-[3.5px]" />
            )}
          </div>
          <div className={`absolute inset-0 rounded-full animate-ping scale-125 opacity-10 ${isSuccess ? 'bg-[#D4A017]' : 'bg-red-500'}`} />
        </div>

        <h2 className="text-2xl font-bold text-white mb-2 tracking-tight text-center">
          {isSuccess ? 'Payment Successful' : 'Payment Declined'}
        </h2>
        <p className="text-gray-500 text-sm text-center mb-10 px-4 leading-relaxed">
          {isSuccess 
            ? 'Your transaction has been processed and funds are on their way.' 
            : 'Unable to process transaction. Please check your balance or network.'}
        </p>

        <div className="w-full bg-[#121214] rounded-[32px] p-6 border border-white/5 space-y-5 mb-8">
          <div className="flex justify-between items-center text-[11px] font-bold uppercase tracking-widest text-gray-500">
            <span>Transaction Details</span>
            <span className="text-[#D4A017]">ID: {transactionData.id}</span>
          </div>

          <div className="space-y-4">
            <div className="flex justify-between items-center">
              <span className="text-gray-400 text-sm">Recipient</span>
              <span className="text-white font-bold text-sm">{transactionData.recipient}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-gray-400 text-sm">Amount</span>
              <span className="text-white font-bold text-sm">{transactionData.amount}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-gray-400 text-sm">Network Fee</span>
              <span className="text-white font-bold text-sm">{transactionData.fee}</span>
            </div>
            <div className="h-px bg-white/5" />
            <div className="flex justify-between items-center">
              <span className="text-gray-400 text-sm font-bold">Total</span>
              <span className="text-[#D4A017] font-bold text-lg">{transactionData.total}</span>
            </div>
          </div>
        </div>

        <div className="w-full grid grid-cols-2 gap-4 mb-4">
          <button 
            onClick={handleShare}
            className="h-14 bg-[#1C1C1E] rounded-2xl flex items-center justify-center text-white border border-white/5 hover:bg-[#252528] transition-all active:scale-95"
            title="Share Receipt"
          >
            <Share2 size={18} />
          </button>
          <button 
            onClick={handleDownload}
            className="h-14 bg-[#1C1C1E] rounded-2xl flex items-center justify-center text-white border border-white/5 hover:bg-[#252528] transition-all active:scale-95"
            title="Download Receipt"
          >
            <Download size={18} />
          </button>
        </div>

        <button
          onClick={onBack}
          className={`w-full h-16 rounded-[24px] font-bold text-base active:scale-95 transition-all shadow-xl ${
            isSuccess 
            ? 'bg-[#D4A017] text-black shadow-yellow-600/10' 
            : 'bg-white text-black'
          }`}
        >
          {isSuccess ? 'Return to Home' : 'Retry Payment'}
        </button>
      </div>

      <div className="h-10 shrink-0" />
    </div>
  );
};

export default Modals;